### PR TITLE
[13.0][MIG] currency_rate_update_oxr

### PR DESCRIPTION
**Pull request by pafnow**
Standard migration

### CODE REVIEW

**Comment by pafnow** [comment]
Since i'm new here, I don't understand the errors Travis is outputting.
Please help me to explain what need to be changed.

**Comment by alexey-pelykh** [comment]
Check on the guideline how it should be performed: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch

**Comment by pafnow** [comment]
Here you go, sorry for the several commits but I needed to get use to that.

**Comment by alexey-pelykh** [comment]
@pafnow please squash the commits correctly according to https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch

**Comment by pafnow** [comment]
done

**Comment by alexey-pelykh** [comment]
Yet I don't see commits from v12 in this PR? Then need to be [almost fully] preserved as per guidelines

**Comment by bosd** [comment]
> I don't see commits from v12 in this PR

How can this be solved? As it would be great to have this one ready to be merged :hugs:

**Comment by alexey-pelykh** [comment]
@bosd no, it was not. This migration needs to be re-done effectively since history is lost

**Comment by yaazkal** [comment]
@pafnow is it possible that you reopen a new PR preserving commits history from 12?

Would be nice to have this addon migrated.

**Pull request closed without merging**
