### PR TITLE
[FIX][11.0] Duplicated view

### PR DESCRIPTION
**Pull request by angelmoya**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Travis is still red

**Comment by angelmoya** [comment]
Travis is red because module account_fx_spot

**Comment by pedrobaeza** [comment]
@lreficent can you please check?

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
Please fix Travis first

**Comment by LoisRForgeFlow** [comment]
Travis should be fixed with: https://github.com/OCA/currency/pull/56

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by angelmoya** [comment]
ok, done

**Comment by LoisRForgeFlow** [comment]
:green_heart:

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
