### PR TITLE
[14.0][MIG] currency_rate_update_transferwise: Migration to 14.0

### PR DESCRIPTION
**Pull request by klodr**

### CODE REVIEW

**Comment by klodr** [comment]
Please Merge

**Comment by BriceCG** [comment]
I was waiting for this module
Thanks for merging

**Comment by R-ando** [comment]
It's good for me, thanks for merging

**Comment by Ihagatiana** [comment]
Thank you please merge

**Comment by razafimiandrisoa** [comment]
You can merge

**Comment by idealsonDEV** [comment]
please merge

**Review by alexis-via — APPROVED** [review]

**Review by BriceCG — APPROVED** [review]

**Review by BriceCG — APPROVED** [review]

**Review by R-ando — APPROVED** [review]

**Review by razafimiandrisoa — APPROVED** [review]

**Review by R-ando — APPROVED** [review]

**Comment by klodr** [comment]
@pedrobaeza if you've rights could you approve and merge ? Thanks

**Pull request merged**
