### PR TITLE
Update view, odoo compatibility.

### PR DESCRIPTION
**Pull request by feketemihai**
Didn't tested locally, but hope it will solve #17 , if not i will continue.

@misuv @moylop260 @pedrobaeza

### CODE REVIEW

**Comment by feketemihai** [comment]
Inheritance is quite a nightmare since only a small amount of block have an id, name or string so we can inherit the right one

**Comment by pedrobaeza** [comment]
Please change version number. Good if this works in all versions.

**Comment by moylop260** [comment]
👍 
Result using a old odoo 11.0 version:
 - screen shot 2018-04-17 at 14 49 45

**Review by moylop260 — APPROVED** [review]
👍 

The warning of runbot is unrelated for this PR

**Comment by feketemihai** [comment]
@moylop260 i will check runbot tomorow, can you check on old odoo if the menu is showing, please.

**Comment by moylop260** [comment]
I have created a dummy commit (please, delete it) in order to create a runbot with a old odoo-11.0
`ssh -p 8221  odoo@runbot2.odoo-community.org -t "(git --git-dir=/home/odoo/odoo-11.0/.git log -r -1)"`

```bash
commit 8836ad52741ff661248a4e268a195da1e645c684 (HEAD -> 11.0-odoo)
Author: Florent de Labarre <florent.mirieu@gmail.com>
Date:   Sun Dec 17 21:32:28 2017 +0100
```

**Comment by feketemihai** [comment]
@moylop260 Looks better now, inline with the config. Thanks.

**Comment by moylop260** [comment]
@pedrobaeza are you agree?

**Comment by pedrobaeza** [comment]
There are warnings in runbot:
```
<string>:34: (WARNING/2) Enumerated list ends without a blank line; unexpected unindent.
<string>:38: (WARNING/2) Enumerated list ends without a blank line; unexpected unindent.
2018-04-18 05:34:51,168 168 WARNING openerp_test odoo.addons.base.module.module: docutils' system message present: <system_message level="2" line="34" source="<string>" type="WARNING"><paragraph>Enumerated list ends without a blank line; unexpected unindent.</paragraph></system_message>
2018-04-18 05:34:51,168 168 WARNING openerp_test odoo.addons.base.module.module: docutils' system message present: <system_message level="2" line="38" source="<string>" type="WARNING"><paragraph>Enumerated list ends without a blank line; unexpected unindent.</paragraph></system_message>
```

**Comment by feketemihai** [comment]
@pedrobaeza It's from currency_rate_update_cmc, do you want to fix them in this PR since it's a different module?

**Comment by pedrobaeza** [comment]
OK, I thought it was this one. Then let's merge this but better to fix the other thing (you can do it via direct commit I think).

**Comment by feketemihai** [comment]
@pedrobaeza In a few minutes...

**Comment by feketemihai** [comment]
@pedrobaeza Seems that i was added and removed from Accounting Maintainers in the same day, waiting for the survey result...

**Pull request merged**
