### PR TITLE
[WIP] [MIG] currency_rate_update_transferwise: Migration to 13.0

### PR DESCRIPTION
**Pull request by ghost**
Ran through https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch

Had to force a charset on pulling of rates as it kept failing to get updates.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Latest commit doesn't comply with black (due to simple quotes), and can be squashed with migration one as part of the tasks to make it work on this version.

You shouldn't open issues for the code you are migrated, as issues are for already merged modules. You may want to comment some troubles on the PR itself if you are not able to fulfill the migration, but present your WiP, and maybe someone can help.

**Comment by ghost** [comment]
Suppose I should have run pre-commit again before pushing my bad sorting this now. Wasn't sure on best practices when it came to #99 that's why I opened it as a ticket. Am I correct in thinking just push it to my PR and it should be ok?

**Comment by pedrobaeza** [comment]
I don't totally understand your words, but the migration commit should contain all the changes you need to do for making the module to work on new version, and no need to split it. Sometimes, a new commit is put if there is new features added at the same time of the migration.

**Comment by ghost** [comment]
Okay will close PR and try again.

**Comment by pedrobaeza** [comment]
You don't need to close it, but rebase interactively the branch to make the squash.

**Pull request closed without merging**
