### PR TITLE
[12.0][MIG] account_fx_spot

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by bosd** [comment]
@MiquelRForgeFlow What is the status of this PR?

**Comment by MiquelRForgeFlow** [comment]
I suppose that is in "to be reviewed" status.

**Comment by bosd** [comment]
Got an server error on a functional test, when registering an payment.
Register Payment error

**Comment by MiquelRForgeFlow** [comment]
Sorry, we don't need this anymore, so I will not dedicate more time to this for the time being.

**Pull request closed without merging**
