### PR TITLE
[12.0][ADD] currency_rate_update_xe: XE.com currency rates provider

### PR DESCRIPTION
**Pull request by alexey-pelykh**
This module provides adds [XE.com](https://xe.com/) currency exchange rates provider.

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@astirpe @pedrobaeza @Nikul-Chaudhary if possible, please review

**Comment by alexey-pelykh** [comment]
@jbeficent @lreficent I'd like to request some fraction of your time to take a look at this module as PSC of the project

**Comment by LoisRForgeFlow** [comment]
@alexey-pelykh I see this is a paid provider. How am I supposed to test this without signing in for the free trial?

**Comment by alexey-pelykh** [comment]
@lreficent unfortunately yes, they are paid, so only via trial or only code review :( they are uncooperative with OSS, but still a good currency rates provider. Though very pricey

**Comment by LoisRForgeFlow** [comment]
It is not cheap indeed, you must have a good reason to need so much accuracy :laughing:

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, looks very clean :+1:

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review and functional test using the Free Trial :+1:

**Pull request merged**
