### PR TITLE
[14.0][IMP] Improve company default get, rates data items if None.

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
A test to cover None case would be great!

**Comment by feketemihai** [comment]
@alexey-pelykh We only found this in our runbot, on not bank days:

2021-03-21 08:37:20 | WARNING | server | odoo.addons.base.models.res_company:186 The method '_company_default_get' on res.company is deprecated and shouldn't be used anymore
-- | -- | -- | --
2021-03-21 08:37:21 | WARNING | server | odoo.addons.currency_rate_update.models.res_currency_rate_provider:140Currency Rate Provider "National Bank of Romania" failed to obtain data since 2021-03-21 until 2021-03-21 Traceback (most recent call last):   File "/data/build/oca-currency/currency_rate_update/models/res_currency_rate_provider.py", line 129, in _update     date_to, AttributeError: 'NoneType' object has no attribute 'items'

and test_update_ECB_today is mentioning this part, it's just a small improvement not to raise warning since we have no data.

**Comment by bosd** [comment]
fix for: https://github.com/OCA/currency/issues/92

**Review by bosd — APPROVED** [review]

**Comment by bosd** [comment]
ooh ooh bot added stale label.
Is tihs PR still needed?

**Pull request closed without merging**
