### PR TITLE
[11.0][mig][currency_rate_update]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Originating from https://github.com/OCA/account-financial-tools/pull/579

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
The module was first proposed by @jesusVMayor and approved by @feketemihai and myself. So moving on and merging this one.

**Comment by pedrobaeza** [comment]
@jbeficent again you are merging without squashing useless commits like your last ones. Please ping me before merging and I can do the squash, but don't merge directly.

**Comment by feketemihai** [comment]
@jbeficent @pedrobaeza Original PR contained splitted modules for each service that was available in V10, i don't see them merged in this repo, how we should treat that ones? New PR here or it should take place in each localization based on the country of the service?

**Comment by pedrobaeza** [comment]
IMO, if they are local to the country, then in the localization repository. If not, new PR here.

**Comment by feketemihai** [comment]
@pedrobaeza Most of them where from countries central banks, so to each localisation then...Thanks.

**Pull request merged**
