### PR TITLE
[11.0][add][currency_rate_update_vn_VCB]

### PR DESCRIPTION
**Pull request by denislour**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Better to add this module in OCA/l10n-vietnam.

**Comment by JordiBForgeFlow** [comment]
Please review your tests. 
It is now not allowed to change the default company currency:
https://github.com/denislour/currency/blob/b47278b5584548bec5b52b522e62000be5e815eb/currency_rate_update_VN_VCB/tests/test_currency_rate_update_vn_vcb.py#L12 

You can apply the same as in https://github.com/OCA/currency/commit/3a5e2230b964fb9a8e8f7771425fee4de86a512d

**Comment by feketemihai** [comment]
@denislour I agree that this should go in localisation repo, please see the romanian one at https://github.com/OCA/l10n-romania/tree/11.0/currency_rate_update_RO_BNR with test updated for main company currency error.

**Comment by feketemihai** [comment]
@pedrobaeza @jbeficent @denislour I think we can close this one, since there a new PR in localization repo.

**Comment by denislour** [comment]
I moved this PR to [l10n-vietnam](https://github.com/OCA/l10n-vietnam/pull/8).

**Pull request closed without merging**
