### PR TITLE
[12.0][MIG] account_cryptocurrency

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
Can you check https://travis-ci.org/OCA/currency/jobs/589440003#L870

**Comment by MiquelRForgeFlow** [comment]
@jbeficent checked and fixed.

**Review by alexey-pelykh — APPROVED** [review]
Code LGTM

**Review by bosd — APPROVED** [review]
Functional LGTM :+1:

**Review by AdriaGForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
