### PR TITLE
[14.0][MIG] currency_monthly_rate: Migration to 14.0

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago  @augustodinizl  @douglascstd

### CODE REVIEW

**Comment by kaynnan** [comment]
ping @grindtildeath

**Comment by kaynnan** [comment]
ping @grindtildeath

**Comment by grindtildeath** [comment]
@kaynnan Thx for the mig
Can you please fix the commit history, because the migration commit [737bce5](https://github.com/OCA/currency/pull/172/commits/737bce5fe1643a2a2b4b61d3d2d182ee28c12f91) includes all the reformatting that is supposed to be done through pre-commit and included in [black, isort, prettier](https://github.com/OCA/currency/pull/172/commits/591738ad07c0dd18e6fe52062aa98ece189237ca) commit?
That will help to review only the changes done for the migration.

**Comment by kaynnan** [comment]
> @kaynnan Thx for the mig Can you please fix the commit history, because the migration commit [737bce5](https://github.com/OCA/currency/pull/172/commits/737bce5fe1643a2a2b4b61d3d2d182ee28c12f91) includes all the reformatting that is supposed to be done through pre-commit and included in [black, isort, prettier](https://github.com/OCA/currency/pull/172/commits/591738ad07c0dd18e6fe52062aa98ece189237ca) commit? That will help to review only the changes done for the migration.

@grindtildeath Thx for the feedback, but the pre-commit commit itself is correct. It was carried out in the commit [591738a](https://github.com/OCA/currency/pull/172/commits/591738ad07c0dd18e6fe52062aa98ece189237ca). The MIG commit changed the manifest and the necessary files for it to work in the new version. Which one would be correct? Because I followed the commit pattern outlined in the guide at [Migration to version 14.0](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0).

**Comment by marcelsavegnago** [comment]
@kaynnan @grindtildeath is right. As we talked about today, make the adjustments because all the changes to isort, black, and prettier were in the migration commit and must remain in the previous commit. Thanks

**Comment by kaynnan** [comment]
@grindtildeath and @marcelsavegnago,

I would like to express my gratitude for the feedback provided regarding the commit history. Taking into account your suggestions, I have made the necessary corrections to improve the quality of the history.

**Comment by marcelsavegnago** [comment]
cc @douglascstd, @augustodinizl

**Review by douglascstd — APPROVED** [review]
[FUNCTIONAL TEST] APPROVED

image

image

image

**Review by marcelsavegnago — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @OCA/currency-maintainers

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
