### PR TITLE
[12.0][IMP] currency_rate_update: use last_successful_run

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Improve/Fix that if update before previous failed, it won't be requeried

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You need migration script for filling `last_successful_run` on existing providers.

**Comment by alexey-pelykh** [comment]
@pedrobaeza it's `None` by default, so it's ok - or I'm not following what you mean.

**Comment by pedrobaeza** [comment]
Oh, I see. OK then.

**Review by pedrobaeza — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@mreficent @novawish if you don't mind, please take a look at this improvement

**Comment by alexey-pelykh** [comment]
@jcdrubay @tbaden please take a look on this one, if possible

**Review by tbaden — APPROVED** [review]
LGTM

**Pull request merged**
