### PR TITLE
[13.0][FIX] currency_rate_update: Change ECB close time to 19 according to https://www.ecb.europa.eu/services/contacts/working-hours/html/index.en.html (18:30)

### PR DESCRIPTION
**Pull request by victoralmau**
Change ECB close time to 19 according to https://www.ecb.europa.eu/services/contacts/working-hours/html/index.en.html (18:30)

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT38444

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by chienandalu** [comment]
> Change ECB close time to 19 according to https://www.ecb.europa.eu/services/contacts/working-hours/html/index.en.html (18:30)
> 

The link states 17:30 CEST

**Comment by victoralmau** [comment]
> 

17:30 in UTC+1 (18:30 in UTC+0)

**Comment by chienandalu** [comment]
> 17:30 in UTC+1 (18:30 in UTC+0)

CET Time is UTC+2 in summer and UTC+1 in winter (https://en.wikipedia.org/wiki/Central_European_Time)

But I guess it's ok as we cover both cases :)

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
