### PR TITLE
[12.0][FIX] currency_rate_update: no data on weekends

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Addresses https://github.com/OCA/currency/issues/62

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@gaikaz please check the fix

**Review by gaikaz — COMMENTED** [review]
Tested and works.
It would probably be a good idea to also add a "Known issues / Roadmap" section to `README.rst`, mentioning that ECB doesn't provide currency rates for weekends and it is currently expected behaviour.

**Comment by alexey-pelykh** [comment]
@pedrobaeza fast-track or not qualified?
@gaikaz well, I don't think it's worth mentioning that banks are closed on non-banking days, so don't expect European Central Bank to be working on official holidays and non-banking days :)

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
