### PR TITLE
[12.0] Add brazilian central bank currency rate provider

### PR DESCRIPTION
**Pull request by renatonlima**
Hi guys,

Here in Brazil, BCB (Brazilian Central Bank) has one currency rate service, https://dadosabertos.bcb.gov.br/dataset/taxas-de-cambio-todos-os-boletins-diarios This PR add in this module this Current rate API.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please do it on an isolated module inside l10n-brazil

**Comment by renatonlima** [comment]
Hi @pedrobaeza thank you for your review,

Is it not better add only one provide as ECB provider? Or create one module inside OCA/currency to add this provide?

**Comment by pedrobaeza** [comment]
If this specific for Brazil, you should put it in OCA/l10n-brazil, not here.

**Comment by alexey-pelykh** [comment]
@renatonlima also please take into account resent change in the API of `currency_rate_update` and feel free to ping me for review of the PR to `OCA/l10n-brazil`

**Comment by renatonlima** [comment]
Thank you @ alexey-pelykh, I will do a PR in OCA / l10n-brazil as recommended by @pedrobaeza and refer this PR and close it.

**Comment by renatonlima** [comment]
Hi guys,

I made one PR in OCA/l10n-brazil#683 to implement Brazilian Central Bank provider

**Pull request closed without merging**
