### PR TITLE
[12.0][FIX] currency_rate_update_oxr: use Token instead of Bearer

### PR DESCRIPTION
**Pull request by alexey-pelykh**
As per https://github.com/OCA/currency/issues/60#issuecomment-518991006 @gaikaz

### CODE REVIEW

**Comment by gaikaz** [comment]
Ok. I didn't fully understand, how the issue got solved that day. Now I see it. I had EUR as base currency too. 🤦‍♂️

Now about this header, is there even a case, where the url parameter `app_id` is missing and header is needed? Does is get parsed out somehow?

**Comment by alexey-pelykh** [comment]
Nope, both Header and `app_id` query parameter is passed :)

**Comment by alexey-pelykh** [comment]
@lreficent any feedback on this?
@gaikaz please review this PR if possible

**Review by gaikaz — APPROVED** [review]
Can't test it functionally right now, but the change LGTM

Though, as I understand, this part of code is just a redundancy for adding the `app_id` if OXR starts prioritizing the http header instead of URL parameter `app_id`, how it is now.

**Pull request merged**
