### PR TITLE
[13.0][FIX] currency_rate_update: Add noupdate=1 to cron record.

### PR DESCRIPTION
**Pull request by victoralmau**
Add noupdate=1 to cron record.

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT32988

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Oh, is this still pending? This should be fixed ASAP

**Comment by pedrobaeza** [comment]
Fast-tracking it:

/ocabot merge minor

Anyways, shouldn't be also the cron to be preset at the proper hour for avoiding the problem?

**Comment by pedrobaeza** [comment]
I mean, here in the module, not manually on the DB.

**Comment by victoralmau** [comment]
Another PR linked with this addon is https://github.com/OCA/currency/pull/85.
I am going to create a new one to v13 because it is quite important to "limit" the time and avoid "ghost" updates.

**Pull request merged**
