### PR TITLE
[14.0][MIG] currency_rate_inverted

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Standard migration of module currency_rate_inverted to v14.

cc ~ @ForgeFlow

### CODE REVIEW

**Comment by bosd** [comment]
is this one ready for review? If so, can you force push to generate a runboat.

**Comment by MiquelRForgeFlow** [comment]
@bosd rebased

**Review by alexey-pelykh — APPROVED** [review]
Code LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by bosd** [comment]
@ocamaintainers please merge

**Comment by MiquelRForgeFlow** [comment]
@OCA/currency-maintainers

**Review by andreampiovesana — APPROVED** [review]
merge!

**Comment by bosd** [comment]
@dreispt  Could you merge? :pray:

**Comment by MiquelRForgeFlow** [comment]
@dreispt

**Pull request merged**
